// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf-c/protobuf-c.proto

#include "protobuf-c/protobuf-c.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_protobuf_2dc_2fprotobuf_2dc_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ProtobufCFieldOptions_protobuf_2dc_2fprotobuf_2dc_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_2dc_2fprotobuf_2dc_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ProtobufCFileOptions_protobuf_2dc_2fprotobuf_2dc_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_2dc_2fprotobuf_2dc_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ProtobufCMessageOptions_protobuf_2dc_2fprotobuf_2dc_2eproto;
class ProtobufCFileOptionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtobufCFileOptions> _instance;
} _ProtobufCFileOptions_default_instance_;
class ProtobufCMessageOptionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtobufCMessageOptions> _instance;
} _ProtobufCMessageOptions_default_instance_;
class ProtobufCFieldOptionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtobufCFieldOptions> _instance;
} _ProtobufCFieldOptions_default_instance_;
static void InitDefaultsProtobufCFileOptions_protobuf_2dc_2fprotobuf_2dc_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ProtobufCFileOptions_default_instance_;
    new (ptr) ::ProtobufCFileOptions();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ProtobufCFileOptions::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ProtobufCFileOptions_protobuf_2dc_2fprotobuf_2dc_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsProtobufCFileOptions_protobuf_2dc_2fprotobuf_2dc_2eproto}, {}};

static void InitDefaultsProtobufCMessageOptions_protobuf_2dc_2fprotobuf_2dc_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.DefaultConstruct();
  *::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get_mutable() = ::std::string("base", 4);
  ::google::protobuf::internal::OnShutdownDestroyString(
      ::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get_mutable());
  {
    void* ptr = &::_ProtobufCMessageOptions_default_instance_;
    new (ptr) ::ProtobufCMessageOptions();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ProtobufCMessageOptions::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ProtobufCMessageOptions_protobuf_2dc_2fprotobuf_2dc_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsProtobufCMessageOptions_protobuf_2dc_2fprotobuf_2dc_2eproto}, {}};

static void InitDefaultsProtobufCFieldOptions_protobuf_2dc_2fprotobuf_2dc_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ProtobufCFieldOptions_default_instance_;
    new (ptr) ::ProtobufCFieldOptions();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ProtobufCFieldOptions::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ProtobufCFieldOptions_protobuf_2dc_2fprotobuf_2dc_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsProtobufCFieldOptions_protobuf_2dc_2fprotobuf_2dc_2eproto}, {}};

void InitDefaults_protobuf_2dc_2fprotobuf_2dc_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ProtobufCFileOptions_protobuf_2dc_2fprotobuf_2dc_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ProtobufCMessageOptions_protobuf_2dc_2fprotobuf_2dc_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ProtobufCFieldOptions_protobuf_2dc_2fprotobuf_2dc_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_protobuf_2dc_2fprotobuf_2dc_2eproto[3];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_protobuf_2dc_2fprotobuf_2dc_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_protobuf_2dc_2fprotobuf_2dc_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_protobuf_2dc_2fprotobuf_2dc_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::ProtobufCFileOptions, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::ProtobufCFileOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ProtobufCFileOptions, no_generate_),
  PROTOBUF_FIELD_OFFSET(::ProtobufCFileOptions, gen_pack_helpers_),
  PROTOBUF_FIELD_OFFSET(::ProtobufCFileOptions, gen_init_helpers_),
  PROTOBUF_FIELD_OFFSET(::ProtobufCFileOptions, const_strings_),
  PROTOBUF_FIELD_OFFSET(::ProtobufCFileOptions, use_oneof_field_name_),
  PROTOBUF_FIELD_OFFSET(::ProtobufCFileOptions, c_package_),
  1,
  4,
  5,
  2,
  3,
  0,
  PROTOBUF_FIELD_OFFSET(::ProtobufCMessageOptions, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::ProtobufCMessageOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ProtobufCMessageOptions, gen_pack_helpers_),
  PROTOBUF_FIELD_OFFSET(::ProtobufCMessageOptions, gen_init_helpers_),
  PROTOBUF_FIELD_OFFSET(::ProtobufCMessageOptions, base_field_name_),
  1,
  2,
  0,
  PROTOBUF_FIELD_OFFSET(::ProtobufCFieldOptions, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::ProtobufCFieldOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ProtobufCFieldOptions, string_as_bytes_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, sizeof(::ProtobufCFileOptions)},
  { 17, 25, sizeof(::ProtobufCMessageOptions)},
  { 28, 34, sizeof(::ProtobufCFieldOptions)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ProtobufCFileOptions_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ProtobufCMessageOptions_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ProtobufCFieldOptions_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_protobuf_2dc_2fprotobuf_2dc_2eproto = {
  {}, AddDescriptors_protobuf_2dc_2fprotobuf_2dc_2eproto, "protobuf-c/protobuf-c.proto", schemas,
  file_default_instances, TableStruct_protobuf_2dc_2fprotobuf_2dc_2eproto::offsets,
  file_level_metadata_protobuf_2dc_2fprotobuf_2dc_2eproto, 3, file_level_enum_descriptors_protobuf_2dc_2fprotobuf_2dc_2eproto, file_level_service_descriptors_protobuf_2dc_2fprotobuf_2dc_2eproto,
};

const char descriptor_table_protodef_protobuf_2dc_2fprotobuf_2dc_2eproto[] =
  "\n\033protobuf-c/protobuf-c.proto\032 google/pr"
  "otobuf/descriptor.proto\"\310\001\n\024ProtobufCFil"
  "eOptions\022\032\n\013no_generate\030\001 \001(\010:\005false\022\036\n\020"
  "gen_pack_helpers\030\002 \001(\010:\004true\022\036\n\020gen_init"
  "_helpers\030\003 \001(\010:\004true\022\034\n\rconst_strings\030\004 "
  "\001(\010:\005false\022#\n\024use_oneof_field_name\030\005 \001(\010"
  ":\005false\022\021\n\tc_package\030\006 \001(\t\"y\n\027ProtobufCM"
  "essageOptions\022\037\n\020gen_pack_helpers\030\001 \001(\010:"
  "\005false\022\036\n\020gen_init_helpers\030\002 \001(\010:\004true\022\035"
  "\n\017base_field_name\030\003 \001(\t:\004base\"7\n\025Protobu"
  "fCFieldOptions\022\036\n\017string_as_bytes\030\001 \001(\010:"
  "\005false:G\n\tpb_c_file\022\034.google.protobuf.Fi"
  "leOptions\030\373\007 \001(\0132\025.ProtobufCFileOptions:"
  "L\n\010pb_c_msg\022\037.google.protobuf.MessageOpt"
  "ions\030\373\007 \001(\0132\030.ProtobufCMessageOptions:J\n"
  "\npb_c_field\022\035.google.protobuf.FieldOptio"
  "ns\030\373\007 \001(\0132\026.ProtobufCFieldOptionsB\005\332\?\002\010\001"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_protobuf_2dc_2fprotobuf_2dc_2eproto = {
  false, InitDefaults_protobuf_2dc_2fprotobuf_2dc_2eproto, 
  descriptor_table_protodef_protobuf_2dc_2fprotobuf_2dc_2eproto,
  "protobuf-c/protobuf-c.proto", &assign_descriptors_table_protobuf_2dc_2fprotobuf_2dc_2eproto, 680,
};

void AddDescriptors_protobuf_2dc_2fprotobuf_2dc_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_google_2fprotobuf_2fdescriptor_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_protobuf_2dc_2fprotobuf_2dc_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_protobuf_2dc_2fprotobuf_2dc_2eproto = []() { AddDescriptors_protobuf_2dc_2fprotobuf_2dc_2eproto(); return true; }();

// ===================================================================

void ProtobufCFileOptions::InitAsDefaultInstance() {
}
class ProtobufCFileOptions::HasBitSetters {
 public:
  static void set_has_no_generate(ProtobufCFileOptions* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static void set_has_gen_pack_helpers(ProtobufCFileOptions* msg) {
    msg->_has_bits_[0] |= 0x00000010u;
  }
  static void set_has_gen_init_helpers(ProtobufCFileOptions* msg) {
    msg->_has_bits_[0] |= 0x00000020u;
  }
  static void set_has_const_strings(ProtobufCFileOptions* msg) {
    msg->_has_bits_[0] |= 0x00000004u;
  }
  static void set_has_use_oneof_field_name(ProtobufCFileOptions* msg) {
    msg->_has_bits_[0] |= 0x00000008u;
  }
  static void set_has_c_package(ProtobufCFileOptions* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtobufCFileOptions::kNoGenerateFieldNumber;
const int ProtobufCFileOptions::kGenPackHelpersFieldNumber;
const int ProtobufCFileOptions::kGenInitHelpersFieldNumber;
const int ProtobufCFileOptions::kConstStringsFieldNumber;
const int ProtobufCFileOptions::kUseOneofFieldNameFieldNumber;
const int ProtobufCFileOptions::kCPackageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtobufCFileOptions::ProtobufCFileOptions()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ProtobufCFileOptions)
}
ProtobufCFileOptions::ProtobufCFileOptions(const ProtobufCFileOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  c_package_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_c_package()) {
    c_package_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.c_package_);
  }
  ::memcpy(&no_generate_, &from.no_generate_,
    static_cast<size_t>(reinterpret_cast<char*>(&gen_init_helpers_) -
    reinterpret_cast<char*>(&no_generate_)) + sizeof(gen_init_helpers_));
  // @@protoc_insertion_point(copy_constructor:ProtobufCFileOptions)
}

void ProtobufCFileOptions::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ProtobufCFileOptions_protobuf_2dc_2fprotobuf_2dc_2eproto.base);
  c_package_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&no_generate_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&use_oneof_field_name_) -
      reinterpret_cast<char*>(&no_generate_)) + sizeof(use_oneof_field_name_));
  gen_pack_helpers_ = true;
  gen_init_helpers_ = true;
}

ProtobufCFileOptions::~ProtobufCFileOptions() {
  // @@protoc_insertion_point(destructor:ProtobufCFileOptions)
  SharedDtor();
}

void ProtobufCFileOptions::SharedDtor() {
  c_package_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ProtobufCFileOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ProtobufCFileOptions& ProtobufCFileOptions::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ProtobufCFileOptions_protobuf_2dc_2fprotobuf_2dc_2eproto.base);
  return *internal_default_instance();
}


void ProtobufCFileOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtobufCFileOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    c_package_.ClearNonDefaultToEmptyNoArena();
  }
  ::memset(&no_generate_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&use_oneof_field_name_) -
      reinterpret_cast<char*>(&no_generate_)) + sizeof(use_oneof_field_name_));
  if (cached_has_bits & 0x00000030u) {
    gen_pack_helpers_ = true;
    gen_init_helpers_ = true;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ProtobufCFileOptions::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ProtobufCFileOptions*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional bool no_generate = 1 [default = false];
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_no_generate(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional bool gen_pack_helpers = 2 [default = true];
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_gen_pack_helpers(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional bool gen_init_helpers = 3 [default = true];
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        msg->set_gen_init_helpers(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional bool const_strings = 4 [default = false];
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 32) goto handle_unusual;
        msg->set_const_strings(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional bool use_oneof_field_name = 5 [default = false];
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 40) goto handle_unusual;
        msg->set_use_oneof_field_name(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional string c_package = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 50) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("ProtobufCFileOptions.c_package");
        object = msg->mutable_c_package();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ProtobufCFileOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ProtobufCFileOptions)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool no_generate = 1 [default = false];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_no_generate(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &no_generate_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool gen_pack_helpers = 2 [default = true];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          HasBitSetters::set_has_gen_pack_helpers(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &gen_pack_helpers_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool gen_init_helpers = 3 [default = true];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {
          HasBitSetters::set_has_gen_init_helpers(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &gen_init_helpers_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool const_strings = 4 [default = false];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (32 & 0xFF)) {
          HasBitSetters::set_has_const_strings(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &const_strings_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool use_oneof_field_name = 5 [default = false];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (40 & 0xFF)) {
          HasBitSetters::set_has_use_oneof_field_name(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &use_oneof_field_name_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string c_package = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (50 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_c_package()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->c_package().data(), static_cast<int>(this->c_package().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ProtobufCFileOptions.c_package");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ProtobufCFileOptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ProtobufCFileOptions)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ProtobufCFileOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ProtobufCFileOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool no_generate = 1 [default = false];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->no_generate(), output);
  }

  // optional bool gen_pack_helpers = 2 [default = true];
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->gen_pack_helpers(), output);
  }

  // optional bool gen_init_helpers = 3 [default = true];
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->gen_init_helpers(), output);
  }

  // optional bool const_strings = 4 [default = false];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->const_strings(), output);
  }

  // optional bool use_oneof_field_name = 5 [default = false];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->use_oneof_field_name(), output);
  }

  // optional string c_package = 6;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->c_package().data(), static_cast<int>(this->c_package().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ProtobufCFileOptions.c_package");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->c_package(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ProtobufCFileOptions)
}

::google::protobuf::uint8* ProtobufCFileOptions::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProtobufCFileOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool no_generate = 1 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->no_generate(), target);
  }

  // optional bool gen_pack_helpers = 2 [default = true];
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->gen_pack_helpers(), target);
  }

  // optional bool gen_init_helpers = 3 [default = true];
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->gen_init_helpers(), target);
  }

  // optional bool const_strings = 4 [default = false];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->const_strings(), target);
  }

  // optional bool use_oneof_field_name = 5 [default = false];
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->use_oneof_field_name(), target);
  }

  // optional string c_package = 6;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->c_package().data(), static_cast<int>(this->c_package().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ProtobufCFileOptions.c_package");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->c_package(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtobufCFileOptions)
  return target;
}

size_t ProtobufCFileOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtobufCFileOptions)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional string c_package = 6;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->c_package());
    }

    // optional bool no_generate = 1 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional bool const_strings = 4 [default = false];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

    // optional bool use_oneof_field_name = 5 [default = false];
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional bool gen_pack_helpers = 2 [default = true];
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 1;
    }

    // optional bool gen_init_helpers = 3 [default = true];
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ProtobufCFileOptions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ProtobufCFileOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtobufCFileOptions* source =
      ::google::protobuf::DynamicCastToGenerated<ProtobufCFileOptions>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ProtobufCFileOptions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ProtobufCFileOptions)
    MergeFrom(*source);
  }
}

void ProtobufCFileOptions::MergeFrom(const ProtobufCFileOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtobufCFileOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      c_package_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.c_package_);
    }
    if (cached_has_bits & 0x00000002u) {
      no_generate_ = from.no_generate_;
    }
    if (cached_has_bits & 0x00000004u) {
      const_strings_ = from.const_strings_;
    }
    if (cached_has_bits & 0x00000008u) {
      use_oneof_field_name_ = from.use_oneof_field_name_;
    }
    if (cached_has_bits & 0x00000010u) {
      gen_pack_helpers_ = from.gen_pack_helpers_;
    }
    if (cached_has_bits & 0x00000020u) {
      gen_init_helpers_ = from.gen_init_helpers_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ProtobufCFileOptions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ProtobufCFileOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtobufCFileOptions::CopyFrom(const ProtobufCFileOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtobufCFileOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufCFileOptions::IsInitialized() const {
  return true;
}

void ProtobufCFileOptions::Swap(ProtobufCFileOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtobufCFileOptions::InternalSwap(ProtobufCFileOptions* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  c_package_.Swap(&other->c_package_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(no_generate_, other->no_generate_);
  swap(const_strings_, other->const_strings_);
  swap(use_oneof_field_name_, other->use_oneof_field_name_);
  swap(gen_pack_helpers_, other->gen_pack_helpers_);
  swap(gen_init_helpers_, other->gen_init_helpers_);
}

::google::protobuf::Metadata ProtobufCFileOptions::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_protobuf_2dc_2fprotobuf_2dc_2eproto);
  return ::file_level_metadata_protobuf_2dc_2fprotobuf_2dc_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ProtobufCMessageOptions::InitAsDefaultInstance() {
}
class ProtobufCMessageOptions::HasBitSetters {
 public:
  static void set_has_gen_pack_helpers(ProtobufCMessageOptions* msg) {
    msg->_has_bits_[0] |= 0x00000002u;
  }
  static void set_has_gen_init_helpers(ProtobufCMessageOptions* msg) {
    msg->_has_bits_[0] |= 0x00000004u;
  }
  static void set_has_base_field_name(ProtobufCMessageOptions* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

::google::protobuf::internal::ExplicitlyConstructed<::std::string> ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_;
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtobufCMessageOptions::kGenPackHelpersFieldNumber;
const int ProtobufCMessageOptions::kGenInitHelpersFieldNumber;
const int ProtobufCMessageOptions::kBaseFieldNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtobufCMessageOptions::ProtobufCMessageOptions()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ProtobufCMessageOptions)
}
ProtobufCMessageOptions::ProtobufCMessageOptions(const ProtobufCMessageOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  base_field_name_.UnsafeSetDefault(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get());
  if (from.has_base_field_name()) {
    base_field_name_.AssignWithDefault(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get(), from.base_field_name_);
  }
  ::memcpy(&gen_pack_helpers_, &from.gen_pack_helpers_,
    static_cast<size_t>(reinterpret_cast<char*>(&gen_init_helpers_) -
    reinterpret_cast<char*>(&gen_pack_helpers_)) + sizeof(gen_init_helpers_));
  // @@protoc_insertion_point(copy_constructor:ProtobufCMessageOptions)
}

void ProtobufCMessageOptions::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ProtobufCMessageOptions_protobuf_2dc_2fprotobuf_2dc_2eproto.base);
  base_field_name_.UnsafeSetDefault(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get());
  gen_pack_helpers_ = false;
  gen_init_helpers_ = true;
}

ProtobufCMessageOptions::~ProtobufCMessageOptions() {
  // @@protoc_insertion_point(destructor:ProtobufCMessageOptions)
  SharedDtor();
}

void ProtobufCMessageOptions::SharedDtor() {
  base_field_name_.DestroyNoArena(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get());
}

void ProtobufCMessageOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ProtobufCMessageOptions& ProtobufCMessageOptions::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ProtobufCMessageOptions_protobuf_2dc_2fprotobuf_2dc_2eproto.base);
  return *internal_default_instance();
}


void ProtobufCMessageOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtobufCMessageOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    base_field_name_.UnsafeMutablePointer()->assign(*&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get());
  }
  if (cached_has_bits & 0x00000006u) {
    gen_pack_helpers_ = false;
    gen_init_helpers_ = true;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ProtobufCMessageOptions::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ProtobufCMessageOptions*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional bool gen_pack_helpers = 1 [default = false];
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_gen_pack_helpers(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional bool gen_init_helpers = 2 [default = true];
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_gen_init_helpers(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // optional string base_field_name = 3 [default = "base"];
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("ProtobufCMessageOptions.base_field_name");
        object = msg->mutable_base_field_name();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8Verify;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8Verify(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ProtobufCMessageOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ProtobufCMessageOptions)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool gen_pack_helpers = 1 [default = false];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_gen_pack_helpers(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &gen_pack_helpers_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool gen_init_helpers = 2 [default = true];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          HasBitSetters::set_has_gen_init_helpers(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &gen_init_helpers_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string base_field_name = 3 [default = "base"];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_base_field_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->base_field_name().data(), static_cast<int>(this->base_field_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ProtobufCMessageOptions.base_field_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ProtobufCMessageOptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ProtobufCMessageOptions)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ProtobufCMessageOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ProtobufCMessageOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool gen_pack_helpers = 1 [default = false];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->gen_pack_helpers(), output);
  }

  // optional bool gen_init_helpers = 2 [default = true];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->gen_init_helpers(), output);
  }

  // optional string base_field_name = 3 [default = "base"];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->base_field_name().data(), static_cast<int>(this->base_field_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ProtobufCMessageOptions.base_field_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->base_field_name(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ProtobufCMessageOptions)
}

::google::protobuf::uint8* ProtobufCMessageOptions::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProtobufCMessageOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool gen_pack_helpers = 1 [default = false];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->gen_pack_helpers(), target);
  }

  // optional bool gen_init_helpers = 2 [default = true];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->gen_init_helpers(), target);
  }

  // optional string base_field_name = 3 [default = "base"];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->base_field_name().data(), static_cast<int>(this->base_field_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ProtobufCMessageOptions.base_field_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->base_field_name(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtobufCMessageOptions)
  return target;
}

size_t ProtobufCMessageOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtobufCMessageOptions)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string base_field_name = 3 [default = "base"];
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->base_field_name());
    }

    // optional bool gen_pack_helpers = 1 [default = false];
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional bool gen_init_helpers = 2 [default = true];
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ProtobufCMessageOptions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ProtobufCMessageOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtobufCMessageOptions* source =
      ::google::protobuf::DynamicCastToGenerated<ProtobufCMessageOptions>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ProtobufCMessageOptions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ProtobufCMessageOptions)
    MergeFrom(*source);
  }
}

void ProtobufCMessageOptions::MergeFrom(const ProtobufCMessageOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtobufCMessageOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _has_bits_[0] |= 0x00000001u;
      base_field_name_.AssignWithDefault(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get(), from.base_field_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      gen_pack_helpers_ = from.gen_pack_helpers_;
    }
    if (cached_has_bits & 0x00000004u) {
      gen_init_helpers_ = from.gen_init_helpers_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ProtobufCMessageOptions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ProtobufCMessageOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtobufCMessageOptions::CopyFrom(const ProtobufCMessageOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtobufCMessageOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufCMessageOptions::IsInitialized() const {
  return true;
}

void ProtobufCMessageOptions::Swap(ProtobufCMessageOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtobufCMessageOptions::InternalSwap(ProtobufCMessageOptions* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  base_field_name_.Swap(&other->base_field_name_, &::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get(),
    GetArenaNoVirtual());
  swap(gen_pack_helpers_, other->gen_pack_helpers_);
  swap(gen_init_helpers_, other->gen_init_helpers_);
}

::google::protobuf::Metadata ProtobufCMessageOptions::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_protobuf_2dc_2fprotobuf_2dc_2eproto);
  return ::file_level_metadata_protobuf_2dc_2fprotobuf_2dc_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ProtobufCFieldOptions::InitAsDefaultInstance() {
}
class ProtobufCFieldOptions::HasBitSetters {
 public:
  static void set_has_string_as_bytes(ProtobufCFieldOptions* msg) {
    msg->_has_bits_[0] |= 0x00000001u;
  }
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtobufCFieldOptions::kStringAsBytesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtobufCFieldOptions::ProtobufCFieldOptions()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ProtobufCFieldOptions)
}
ProtobufCFieldOptions::ProtobufCFieldOptions(const ProtobufCFieldOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  string_as_bytes_ = from.string_as_bytes_;
  // @@protoc_insertion_point(copy_constructor:ProtobufCFieldOptions)
}

void ProtobufCFieldOptions::SharedCtor() {
  string_as_bytes_ = false;
}

ProtobufCFieldOptions::~ProtobufCFieldOptions() {
  // @@protoc_insertion_point(destructor:ProtobufCFieldOptions)
  SharedDtor();
}

void ProtobufCFieldOptions::SharedDtor() {
}

void ProtobufCFieldOptions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ProtobufCFieldOptions& ProtobufCFieldOptions::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ProtobufCFieldOptions_protobuf_2dc_2fprotobuf_2dc_2eproto.base);
  return *internal_default_instance();
}


void ProtobufCFieldOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtobufCFieldOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  string_as_bytes_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ProtobufCFieldOptions::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ProtobufCFieldOptions*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // optional bool string_as_bytes = 1 [default = false];
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_string_as_bytes(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ProtobufCFieldOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ProtobufCFieldOptions)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool string_as_bytes = 1 [default = false];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          HasBitSetters::set_has_string_as_bytes(this);
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &string_as_bytes_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ProtobufCFieldOptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ProtobufCFieldOptions)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ProtobufCFieldOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ProtobufCFieldOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool string_as_bytes = 1 [default = false];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->string_as_bytes(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ProtobufCFieldOptions)
}

::google::protobuf::uint8* ProtobufCFieldOptions::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProtobufCFieldOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional bool string_as_bytes = 1 [default = false];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->string_as_bytes(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtobufCFieldOptions)
  return target;
}

size_t ProtobufCFieldOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtobufCFieldOptions)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional bool string_as_bytes = 1 [default = false];
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ProtobufCFieldOptions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ProtobufCFieldOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtobufCFieldOptions* source =
      ::google::protobuf::DynamicCastToGenerated<ProtobufCFieldOptions>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ProtobufCFieldOptions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ProtobufCFieldOptions)
    MergeFrom(*source);
  }
}

void ProtobufCFieldOptions::MergeFrom(const ProtobufCFieldOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtobufCFieldOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_string_as_bytes()) {
    set_string_as_bytes(from.string_as_bytes());
  }
}

void ProtobufCFieldOptions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ProtobufCFieldOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtobufCFieldOptions::CopyFrom(const ProtobufCFieldOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtobufCFieldOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtobufCFieldOptions::IsInitialized() const {
  return true;
}

void ProtobufCFieldOptions::Swap(ProtobufCFieldOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtobufCFieldOptions::InternalSwap(ProtobufCFieldOptions* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(string_as_bytes_, other->string_as_bytes_);
}

::google::protobuf::Metadata ProtobufCFieldOptions::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_protobuf_2dc_2fprotobuf_2dc_2eproto);
  return ::file_level_metadata_protobuf_2dc_2fprotobuf_2dc_2eproto[kIndexInFileMessages];
}

::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::ProtobufCFileOptions >, 11, false >
  pb_c_file(kPbCFileFieldNumber, *::ProtobufCFileOptions::internal_default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::ProtobufCMessageOptions >, 11, false >
  pb_c_msg(kPbCMsgFieldNumber, *::ProtobufCMessageOptions::internal_default_instance());
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::ProtobufCFieldOptions >, 11, false >
  pb_c_field(kPbCFieldFieldNumber, *::ProtobufCFieldOptions::internal_default_instance());

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::ProtobufCFileOptions* Arena::CreateMaybeMessage< ::ProtobufCFileOptions >(Arena* arena) {
  return Arena::CreateInternal< ::ProtobufCFileOptions >(arena);
}
template<> PROTOBUF_NOINLINE ::ProtobufCMessageOptions* Arena::CreateMaybeMessage< ::ProtobufCMessageOptions >(Arena* arena) {
  return Arena::CreateInternal< ::ProtobufCMessageOptions >(arena);
}
template<> PROTOBUF_NOINLINE ::ProtobufCFieldOptions* Arena::CreateMaybeMessage< ::ProtobufCFieldOptions >(Arena* arena) {
  return Arena::CreateInternal< ::ProtobufCFieldOptions >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
