// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf-c/protobuf-c.proto

#ifndef PROTOBUF_INCLUDED_protobuf_2dc_2fprotobuf_2dc_2eproto
#define PROTOBUF_INCLUDED_protobuf_2dc_2fprotobuf_2dc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protobuf_2dc_2fprotobuf_2dc_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_protobuf_2dc_2fprotobuf_2dc_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_protobuf_2dc_2fprotobuf_2dc_2eproto();
class ProtobufCFieldOptions;
class ProtobufCFieldOptionsDefaultTypeInternal;
extern ProtobufCFieldOptionsDefaultTypeInternal _ProtobufCFieldOptions_default_instance_;
class ProtobufCFileOptions;
class ProtobufCFileOptionsDefaultTypeInternal;
extern ProtobufCFileOptionsDefaultTypeInternal _ProtobufCFileOptions_default_instance_;
class ProtobufCMessageOptions;
class ProtobufCMessageOptionsDefaultTypeInternal;
extern ProtobufCMessageOptionsDefaultTypeInternal _ProtobufCMessageOptions_default_instance_;
namespace google {
namespace protobuf {
template<> ::ProtobufCFieldOptions* Arena::CreateMaybeMessage<::ProtobufCFieldOptions>(Arena*);
template<> ::ProtobufCFileOptions* Arena::CreateMaybeMessage<::ProtobufCFileOptions>(Arena*);
template<> ::ProtobufCMessageOptions* Arena::CreateMaybeMessage<::ProtobufCMessageOptions>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class ProtobufCFileOptions :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ProtobufCFileOptions) */ {
 public:
  ProtobufCFileOptions();
  virtual ~ProtobufCFileOptions();

  ProtobufCFileOptions(const ProtobufCFileOptions& from);

  inline ProtobufCFileOptions& operator=(const ProtobufCFileOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProtobufCFileOptions(ProtobufCFileOptions&& from) noexcept
    : ProtobufCFileOptions() {
    *this = ::std::move(from);
  }

  inline ProtobufCFileOptions& operator=(ProtobufCFileOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ProtobufCFileOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtobufCFileOptions* internal_default_instance() {
    return reinterpret_cast<const ProtobufCFileOptions*>(
               &_ProtobufCFileOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ProtobufCFileOptions* other);
  friend void swap(ProtobufCFileOptions& a, ProtobufCFileOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProtobufCFileOptions* New() const final {
    return CreateMaybeMessage<ProtobufCFileOptions>(nullptr);
  }

  ProtobufCFileOptions* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProtobufCFileOptions>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProtobufCFileOptions& from);
  void MergeFrom(const ProtobufCFileOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtobufCFileOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string c_package = 6;
  bool has_c_package() const;
  void clear_c_package();
  static const int kCPackageFieldNumber = 6;
  const ::std::string& c_package() const;
  void set_c_package(const ::std::string& value);
  #if LANG_CXX11
  void set_c_package(::std::string&& value);
  #endif
  void set_c_package(const char* value);
  void set_c_package(const char* value, size_t size);
  ::std::string* mutable_c_package();
  ::std::string* release_c_package();
  void set_allocated_c_package(::std::string* c_package);

  // optional bool no_generate = 1 [default = false];
  bool has_no_generate() const;
  void clear_no_generate();
  static const int kNoGenerateFieldNumber = 1;
  bool no_generate() const;
  void set_no_generate(bool value);

  // optional bool const_strings = 4 [default = false];
  bool has_const_strings() const;
  void clear_const_strings();
  static const int kConstStringsFieldNumber = 4;
  bool const_strings() const;
  void set_const_strings(bool value);

  // optional bool use_oneof_field_name = 5 [default = false];
  bool has_use_oneof_field_name() const;
  void clear_use_oneof_field_name();
  static const int kUseOneofFieldNameFieldNumber = 5;
  bool use_oneof_field_name() const;
  void set_use_oneof_field_name(bool value);

  // optional bool gen_pack_helpers = 2 [default = true];
  bool has_gen_pack_helpers() const;
  void clear_gen_pack_helpers();
  static const int kGenPackHelpersFieldNumber = 2;
  bool gen_pack_helpers() const;
  void set_gen_pack_helpers(bool value);

  // optional bool gen_init_helpers = 3 [default = true];
  bool has_gen_init_helpers() const;
  void clear_gen_init_helpers();
  static const int kGenInitHelpersFieldNumber = 3;
  bool gen_init_helpers() const;
  void set_gen_init_helpers(bool value);

  // @@protoc_insertion_point(class_scope:ProtobufCFileOptions)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr c_package_;
  bool no_generate_;
  bool const_strings_;
  bool use_oneof_field_name_;
  bool gen_pack_helpers_;
  bool gen_init_helpers_;
  friend struct ::TableStruct_protobuf_2dc_2fprotobuf_2dc_2eproto;
};
// -------------------------------------------------------------------

class ProtobufCMessageOptions :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ProtobufCMessageOptions) */ {
 public:
  ProtobufCMessageOptions();
  virtual ~ProtobufCMessageOptions();

  ProtobufCMessageOptions(const ProtobufCMessageOptions& from);

  inline ProtobufCMessageOptions& operator=(const ProtobufCMessageOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProtobufCMessageOptions(ProtobufCMessageOptions&& from) noexcept
    : ProtobufCMessageOptions() {
    *this = ::std::move(from);
  }

  inline ProtobufCMessageOptions& operator=(ProtobufCMessageOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ProtobufCMessageOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtobufCMessageOptions* internal_default_instance() {
    return reinterpret_cast<const ProtobufCMessageOptions*>(
               &_ProtobufCMessageOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ProtobufCMessageOptions* other);
  friend void swap(ProtobufCMessageOptions& a, ProtobufCMessageOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProtobufCMessageOptions* New() const final {
    return CreateMaybeMessage<ProtobufCMessageOptions>(nullptr);
  }

  ProtobufCMessageOptions* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProtobufCMessageOptions>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProtobufCMessageOptions& from);
  void MergeFrom(const ProtobufCMessageOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtobufCMessageOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string base_field_name = 3 [default = "base"];
  bool has_base_field_name() const;
  void clear_base_field_name();
  static const int kBaseFieldNameFieldNumber = 3;
  const ::std::string& base_field_name() const;
  void set_base_field_name(const ::std::string& value);
  #if LANG_CXX11
  void set_base_field_name(::std::string&& value);
  #endif
  void set_base_field_name(const char* value);
  void set_base_field_name(const char* value, size_t size);
  ::std::string* mutable_base_field_name();
  ::std::string* release_base_field_name();
  void set_allocated_base_field_name(::std::string* base_field_name);

  // optional bool gen_pack_helpers = 1 [default = false];
  bool has_gen_pack_helpers() const;
  void clear_gen_pack_helpers();
  static const int kGenPackHelpersFieldNumber = 1;
  bool gen_pack_helpers() const;
  void set_gen_pack_helpers(bool value);

  // optional bool gen_init_helpers = 2 [default = true];
  bool has_gen_init_helpers() const;
  void clear_gen_init_helpers();
  static const int kGenInitHelpersFieldNumber = 2;
  bool gen_init_helpers() const;
  void set_gen_init_helpers(bool value);

  // @@protoc_insertion_point(class_scope:ProtobufCMessageOptions)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  public:
  static ::google::protobuf::internal::ExplicitlyConstructed<::std::string> _i_give_permission_to_break_this_code_default_base_field_name_;
  private:
  ::google::protobuf::internal::ArenaStringPtr base_field_name_;
  bool gen_pack_helpers_;
  bool gen_init_helpers_;
  friend struct ::TableStruct_protobuf_2dc_2fprotobuf_2dc_2eproto;
};
// -------------------------------------------------------------------

class ProtobufCFieldOptions :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ProtobufCFieldOptions) */ {
 public:
  ProtobufCFieldOptions();
  virtual ~ProtobufCFieldOptions();

  ProtobufCFieldOptions(const ProtobufCFieldOptions& from);

  inline ProtobufCFieldOptions& operator=(const ProtobufCFieldOptions& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProtobufCFieldOptions(ProtobufCFieldOptions&& from) noexcept
    : ProtobufCFieldOptions() {
    *this = ::std::move(from);
  }

  inline ProtobufCFieldOptions& operator=(ProtobufCFieldOptions&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ProtobufCFieldOptions& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtobufCFieldOptions* internal_default_instance() {
    return reinterpret_cast<const ProtobufCFieldOptions*>(
               &_ProtobufCFieldOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ProtobufCFieldOptions* other);
  friend void swap(ProtobufCFieldOptions& a, ProtobufCFieldOptions& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProtobufCFieldOptions* New() const final {
    return CreateMaybeMessage<ProtobufCFieldOptions>(nullptr);
  }

  ProtobufCFieldOptions* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProtobufCFieldOptions>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProtobufCFieldOptions& from);
  void MergeFrom(const ProtobufCFieldOptions& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtobufCFieldOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool string_as_bytes = 1 [default = false];
  bool has_string_as_bytes() const;
  void clear_string_as_bytes();
  static const int kStringAsBytesFieldNumber = 1;
  bool string_as_bytes() const;
  void set_string_as_bytes(bool value);

  // @@protoc_insertion_point(class_scope:ProtobufCFieldOptions)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  bool string_as_bytes_;
  friend struct ::TableStruct_protobuf_2dc_2fprotobuf_2dc_2eproto;
};
// ===================================================================

static const int kPbCFileFieldNumber = 1019;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::ProtobufCFileOptions >, 11, false >
  pb_c_file;
static const int kPbCMsgFieldNumber = 1019;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::ProtobufCMessageOptions >, 11, false >
  pb_c_msg;
static const int kPbCFieldFieldNumber = 1019;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::ProtobufCFieldOptions >, 11, false >
  pb_c_field;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProtobufCFileOptions

// optional bool no_generate = 1 [default = false];
inline bool ProtobufCFileOptions::has_no_generate() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtobufCFileOptions::clear_no_generate() {
  no_generate_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool ProtobufCFileOptions::no_generate() const {
  // @@protoc_insertion_point(field_get:ProtobufCFileOptions.no_generate)
  return no_generate_;
}
inline void ProtobufCFileOptions::set_no_generate(bool value) {
  _has_bits_[0] |= 0x00000002u;
  no_generate_ = value;
  // @@protoc_insertion_point(field_set:ProtobufCFileOptions.no_generate)
}

// optional bool gen_pack_helpers = 2 [default = true];
inline bool ProtobufCFileOptions::has_gen_pack_helpers() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ProtobufCFileOptions::clear_gen_pack_helpers() {
  gen_pack_helpers_ = true;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool ProtobufCFileOptions::gen_pack_helpers() const {
  // @@protoc_insertion_point(field_get:ProtobufCFileOptions.gen_pack_helpers)
  return gen_pack_helpers_;
}
inline void ProtobufCFileOptions::set_gen_pack_helpers(bool value) {
  _has_bits_[0] |= 0x00000010u;
  gen_pack_helpers_ = value;
  // @@protoc_insertion_point(field_set:ProtobufCFileOptions.gen_pack_helpers)
}

// optional bool gen_init_helpers = 3 [default = true];
inline bool ProtobufCFileOptions::has_gen_init_helpers() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ProtobufCFileOptions::clear_gen_init_helpers() {
  gen_init_helpers_ = true;
  _has_bits_[0] &= ~0x00000020u;
}
inline bool ProtobufCFileOptions::gen_init_helpers() const {
  // @@protoc_insertion_point(field_get:ProtobufCFileOptions.gen_init_helpers)
  return gen_init_helpers_;
}
inline void ProtobufCFileOptions::set_gen_init_helpers(bool value) {
  _has_bits_[0] |= 0x00000020u;
  gen_init_helpers_ = value;
  // @@protoc_insertion_point(field_set:ProtobufCFileOptions.gen_init_helpers)
}

// optional bool const_strings = 4 [default = false];
inline bool ProtobufCFileOptions::has_const_strings() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtobufCFileOptions::clear_const_strings() {
  const_strings_ = false;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool ProtobufCFileOptions::const_strings() const {
  // @@protoc_insertion_point(field_get:ProtobufCFileOptions.const_strings)
  return const_strings_;
}
inline void ProtobufCFileOptions::set_const_strings(bool value) {
  _has_bits_[0] |= 0x00000004u;
  const_strings_ = value;
  // @@protoc_insertion_point(field_set:ProtobufCFileOptions.const_strings)
}

// optional bool use_oneof_field_name = 5 [default = false];
inline bool ProtobufCFileOptions::has_use_oneof_field_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProtobufCFileOptions::clear_use_oneof_field_name() {
  use_oneof_field_name_ = false;
  _has_bits_[0] &= ~0x00000008u;
}
inline bool ProtobufCFileOptions::use_oneof_field_name() const {
  // @@protoc_insertion_point(field_get:ProtobufCFileOptions.use_oneof_field_name)
  return use_oneof_field_name_;
}
inline void ProtobufCFileOptions::set_use_oneof_field_name(bool value) {
  _has_bits_[0] |= 0x00000008u;
  use_oneof_field_name_ = value;
  // @@protoc_insertion_point(field_set:ProtobufCFileOptions.use_oneof_field_name)
}

// optional string c_package = 6;
inline bool ProtobufCFileOptions::has_c_package() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtobufCFileOptions::clear_c_package() {
  c_package_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& ProtobufCFileOptions::c_package() const {
  // @@protoc_insertion_point(field_get:ProtobufCFileOptions.c_package)
  return c_package_.GetNoArena();
}
inline void ProtobufCFileOptions::set_c_package(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  c_package_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ProtobufCFileOptions.c_package)
}
#if LANG_CXX11
inline void ProtobufCFileOptions::set_c_package(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  c_package_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ProtobufCFileOptions.c_package)
}
#endif
inline void ProtobufCFileOptions::set_c_package(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  c_package_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ProtobufCFileOptions.c_package)
}
inline void ProtobufCFileOptions::set_c_package(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  c_package_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ProtobufCFileOptions.c_package)
}
inline ::std::string* ProtobufCFileOptions::mutable_c_package() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:ProtobufCFileOptions.c_package)
  return c_package_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProtobufCFileOptions::release_c_package() {
  // @@protoc_insertion_point(field_release:ProtobufCFileOptions.c_package)
  if (!has_c_package()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return c_package_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProtobufCFileOptions::set_allocated_c_package(::std::string* c_package) {
  if (c_package != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  c_package_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), c_package);
  // @@protoc_insertion_point(field_set_allocated:ProtobufCFileOptions.c_package)
}

// -------------------------------------------------------------------

// ProtobufCMessageOptions

// optional bool gen_pack_helpers = 1 [default = false];
inline bool ProtobufCMessageOptions::has_gen_pack_helpers() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtobufCMessageOptions::clear_gen_pack_helpers() {
  gen_pack_helpers_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool ProtobufCMessageOptions::gen_pack_helpers() const {
  // @@protoc_insertion_point(field_get:ProtobufCMessageOptions.gen_pack_helpers)
  return gen_pack_helpers_;
}
inline void ProtobufCMessageOptions::set_gen_pack_helpers(bool value) {
  _has_bits_[0] |= 0x00000002u;
  gen_pack_helpers_ = value;
  // @@protoc_insertion_point(field_set:ProtobufCMessageOptions.gen_pack_helpers)
}

// optional bool gen_init_helpers = 2 [default = true];
inline bool ProtobufCMessageOptions::has_gen_init_helpers() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProtobufCMessageOptions::clear_gen_init_helpers() {
  gen_init_helpers_ = true;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool ProtobufCMessageOptions::gen_init_helpers() const {
  // @@protoc_insertion_point(field_get:ProtobufCMessageOptions.gen_init_helpers)
  return gen_init_helpers_;
}
inline void ProtobufCMessageOptions::set_gen_init_helpers(bool value) {
  _has_bits_[0] |= 0x00000004u;
  gen_init_helpers_ = value;
  // @@protoc_insertion_point(field_set:ProtobufCMessageOptions.gen_init_helpers)
}

// optional string base_field_name = 3 [default = "base"];
inline bool ProtobufCMessageOptions::has_base_field_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtobufCMessageOptions::clear_base_field_name() {
  base_field_name_.ClearToDefaultNoArena(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& ProtobufCMessageOptions::base_field_name() const {
  // @@protoc_insertion_point(field_get:ProtobufCMessageOptions.base_field_name)
  return base_field_name_.GetNoArena();
}
inline void ProtobufCMessageOptions::set_base_field_name(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  base_field_name_.SetNoArena(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get(), value);
  // @@protoc_insertion_point(field_set:ProtobufCMessageOptions.base_field_name)
}
#if LANG_CXX11
inline void ProtobufCMessageOptions::set_base_field_name(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  base_field_name_.SetNoArena(
    &::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ProtobufCMessageOptions.base_field_name)
}
#endif
inline void ProtobufCMessageOptions::set_base_field_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  base_field_name_.SetNoArena(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ProtobufCMessageOptions.base_field_name)
}
inline void ProtobufCMessageOptions::set_base_field_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  base_field_name_.SetNoArena(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ProtobufCMessageOptions.base_field_name)
}
inline ::std::string* ProtobufCMessageOptions::mutable_base_field_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:ProtobufCMessageOptions.base_field_name)
  return base_field_name_.MutableNoArena(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get());
}
inline ::std::string* ProtobufCMessageOptions::release_base_field_name() {
  // @@protoc_insertion_point(field_release:ProtobufCMessageOptions.base_field_name)
  if (!has_base_field_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return base_field_name_.ReleaseNonDefaultNoArena(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get());
}
inline void ProtobufCMessageOptions::set_allocated_base_field_name(::std::string* base_field_name) {
  if (base_field_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  base_field_name_.SetAllocatedNoArena(&::ProtobufCMessageOptions::_i_give_permission_to_break_this_code_default_base_field_name_.get(), base_field_name);
  // @@protoc_insertion_point(field_set_allocated:ProtobufCMessageOptions.base_field_name)
}

// -------------------------------------------------------------------

// ProtobufCFieldOptions

// optional bool string_as_bytes = 1 [default = false];
inline bool ProtobufCFieldOptions::has_string_as_bytes() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtobufCFieldOptions::clear_string_as_bytes() {
  string_as_bytes_ = false;
  _has_bits_[0] &= ~0x00000001u;
}
inline bool ProtobufCFieldOptions::string_as_bytes() const {
  // @@protoc_insertion_point(field_get:ProtobufCFieldOptions.string_as_bytes)
  return string_as_bytes_;
}
inline void ProtobufCFieldOptions::set_string_as_bytes(bool value) {
  _has_bits_[0] |= 0x00000001u;
  string_as_bytes_ = value;
  // @@protoc_insertion_point(field_set:ProtobufCFieldOptions.string_as_bytes)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_protobuf_2dc_2fprotobuf_2dc_2eproto
